apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
        service: springboot_service
        env: prd
        owner: jacky
      annotations:
        ad.datadoghq.com/springbootapp.check_names: '["openmetrics"]'
        ad.datadoghq.com/springbootapp.init_configs: '[{}]'
        ad.datadoghq.com/springbootapp.instances: '[{"prometheus_url":"http://%%host%%:%%port%%/actuator/prometheus","metrics":["*"],"namespace":"springboot"}]'
        ad.datadoghq.com/springbootapp.logs: '[{"source":"springbootapp","service":"springboot_service"}]'
    spec:
      containers:
      - name: springbootapp
        image: zmiao1/sample_springboot:015
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_AGENT_PORT
          value: '8126'
        - name: DD_SERVICE_NAME
          value: 'springboot_service'
        - name: DD_TRACE_GLOBAL_TAGS
          value: 'env:prd'
        - name: DD_JMXFETCH_ENABLED
          value: "true"
        - name: DD_STATSD_PORT
          value: '8125'
        - name: DD_JMXFETCH_STATSD_PORT
          value: '8125'
        - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
          value: '{"owner":"owner","category":"category","app":"application","service":"service","env":"env"}'
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp
spec:
  selector:
    app: springbootapp
  ports:
  - name: http
    protocol: TCP
    port: 8080
  type: LoadBalancer
